version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network


  ts-ui-dashboard:
    build: ts-ui-dashboard
    image: containers.github.scch.at/contest/trainticket/ts-ui-dashboard:error-f4
    restart: always
    ports:
      - 80:8080
    networks:
      - my-network

  ts-login-service:
    build: ts-login-service
    image: containers.github.scch.at/contest/trainticket/ts-login-service:error-f4
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network

  ts-account-mongo:
    image: mongo:4.4
    networks:
      - my-network

  ts-route-service:
    build: ts-route-service
    image: containers.github.scch.at/contest/trainticket/ts-route-service:error-f4
    restart: always
    ports:
         - 11178:11178
    networks:
      - my-network

  ts-route-mongo:
    image: mongo:4.4
    networks:
        - my-network


  ts-register-service:
    build: ts-register-service
    image: containers.github.scch.at/contest/trainticket/ts-register-service:error-f4
    restart: always
    ports:
      - 12344:12344
    networks:
      - my-network


  ts-sso-service:
    build: ts-sso-service
    image: containers.github.scch.at/contest/trainticket/ts-sso-service:error-f4
    restart: always
    ports:
      - 12349:12349
    networks:
      - my-network



  ts-verification-code-service:
    build: ts-verification-code-service
    image: containers.github.scch.at/contest/trainticket/ts-verification-code-service:error-f4
    restart: always
    ports:
      - 15678:15678
    networks:
      - my-network

  ts-verification-code-mongo:
    image: mongo:4.4
    networks:
        - my-network

  ts-contacts-service:
    build: ts-contacts-service
    image: containers.github.scch.at/contest/trainticket/ts-contacts-service:error-f4
    restart: always
    ports:
      - 12347:12347
    networks:
      - my-network

  ts-contacts-mongo:
      image: mongo:4.4
      networks:
        - my-network

  ts-order-service:
    build: ts-order-service
    image: containers.github.scch.at/contest/trainticket/ts-order-service:error-f4
    restart: always
    ports:
      - 12031:12031
    networks:
      - my-network

  ts-order-mongo:
    image: mongo:4.4
    networks:
      - my-network


  ts-order-other-service:
    build: ts-order-other-service
    image: containers.github.scch.at/contest/trainticket/ts-order-other-service:error-f4
    restart: always
    ports:
      - 12032:12032
    networks:
      - my-network

  ts-order-other-mongo:
    image: mongo:4.4
    networks:
      - my-network


  ts-config-service:
    build: ts-config-service
    image: containers.github.scch.at/contest/trainticket/ts-config-service:error-f4
    restart: always
    ports:
      - 15679:15679
    networks:
      - my-network

  ts-config-mongo:
    image: mongo:4.4
    networks:
      - my-network

  ts-station-service:
    build: ts-station-service
    image: containers.github.scch.at/contest/trainticket/ts-station-service:error-f4
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-station-mongo:
    image: mongo:4.4
    networks:
      - my-network

  ts-train-service:
    build: ts-train-service
    image: containers.github.scch.at/contest/trainticket/ts-train-service:error-f4
    restart: always
    ports:
      - 14567:14567
    networks:
      - my-network

  ts-train-mongo:
    image: mongo:4.4
    networks:
      - my-network

  ts-travel-service:
    build: ts-travel-service
    image: containers.github.scch.at/contest/trainticket/ts-travel-service:error-f4
    restart: always
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel-mongo:
    image: mongo:4.4
    networks:
      - my-network

  ts-travel2-service:
      build: ts-travel2-service
      image: containers.github.scch.at/contest/trainticket/ts-travel2-service:error-f4
      restart: always
      ports:
        - 16346:16346
      networks:
        - my-network

  ts-travel2-mongo:
      image: mongo:4.4
      networks:
        - my-network

  ts-preserve-service:
    build: ts-preserve-service
    image: containers.github.scch.at/contest/trainticket/ts-preserve-service:error-f4
    restart: always
    ports:
      - 14568:14568
    networks:
      - my-network

  ts-preserve-other-service:
    build: ts-preserve-other-service
    image: containers.github.scch.at/contest/trainticket/ts-preserve-other-service:error-f4
    restart: always
    ports:
      - 14569:14569
    networks:
      - my-network


  ts-basic-service:
      build: ts-basic-service
      image: containers.github.scch.at/contest/trainticket/ts-basic-service:error-f4
      restart: always
      ports:
        - 15680:15680
      networks:
          - my-network

  ts-ticketinfo-service:
        build: ts-ticketinfo-service
        image: containers.github.scch.at/contest/trainticket/ts-ticketinfo-service:error-f4
        restart: always
        ports:
          - 15681:15681
        networks:
          - my-network

  ts-price-service:
        build: ts-price-service
        image: containers.github.scch.at/contest/trainticket/ts-price-service:error-f4
        restart: always
        ports:
          - 16579:16579
        networks:
          - my-network

  ts-price-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-notification-service:
        build: ts-notification-service
        image: containers.github.scch.at/contest/trainticket/ts-notification-service:error-f4
        restart: always
        ports:
          - 17853:17853
        networks:
          - my-network

  ts-security-service:
        build: ts-security-service
        image: containers.github.scch.at/contest/trainticket/ts-security-service:error-f4
        restart: always
        ports:
          - 11188:11188
        networks:
          - my-network

  ts-security-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-inside-payment-service:
        build: ts-inside-payment-service
        image: containers.github.scch.at/contest/trainticket/ts-inside-payment-service:error-f4
        restart: always
        ports:
          - 18673:18673
        networks:
          - my-network

  ts-inside-payment-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-execute-service:
        build: ts-execute-service
        image: containers.github.scch.at/contest/trainticket/ts-execute-service:error-f4
        restart: always
        ports:
          - 12386:12386
        networks:
          - my-network

  ts-payment-service:
        build: ts-payment-service
        image: containers.github.scch.at/contest/trainticket/ts-payment-service:error-f4
        restart: always
        ports:
          - 19001:19001
        networks:
          - my-network

  ts-payment-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-rebook-service:
        build: ts-rebook-service
        image: containers.github.scch.at/contest/trainticket/ts-rebook-service:error-f4
        restart: always
        ports:
          - 18886:18886
        networks:
          - my-network

  ts-rebook-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-cancel-service:
        build: ts-cancel-service
        image: containers.github.scch.at/contest/trainticket/ts-cancel-service:error-f4
        restart: always
        ports:
          - 18885:18885
        networks:
          - my-network

  ts-assurance-service:
        build: ts-assurance-service
        image: containers.github.scch.at/contest/trainticket/ts-assurance-service:error-f4
        restart: always
        ports:
          - 18888:18888
        networks:
          - my-network

  ts-assurance-mongo:
        image: mongo:4.4
        networks:
          - my-network

  ts-seat-service:
        build: ts-seat-service
        image: containers.github.scch.at/contest/trainticket/ts-seat-service:error-f4
        restart: always
        ports:
          - 18898:18898
        networks:
          - my-network

  ts-travel-plan-service:
        build: ts-travel-plan-service
        image: containers.github.scch.at/contest/trainticket/ts-travel-plan-service:error-f4
        restart: always
        ports:
          - 14322:14322
        networks:
          - my-network

  ts-ticket-office-service:
        build: ts-ticket-office-service
        image: containers.github.scch.at/contest/trainticket/ts-ticket-office-service:error-f4
        restart: always
        ports:
          - 16108:16108
        networks:
          - my-network

  ts-ticket-office-mongo:
          image: mongo:4.4
          networks:
            - my-network

  ts-news-service:
    build: ts-news-service
    image: containers.github.scch.at/contest/trainticket/ts-news-service:error-f4
    restart: always
    ports:
      - 12862:12862
    networks:
      - my-network

  ts-news-mongo:
        image: mongo:4.4
        networks:
          - my-network

#  ts-voucher-mysql:
#         image: mysql
#         expose:
#            - "3306"
#         environment:
#           MYSQL_ROOT_PASSWORD: root
#         networks:
#           - my-network
#
#  ts-voucher-service:
#          build: ts-voucher-service
#          image: containers.github.scch.at/contest/trainticket/ts-voucher-service:error-f4
#          restart: always
#          ports:
#            - 16101:16101
#          depends_on:
#            - ts-voucher-mysql
#          volumes:
#            - /var/lib/mysql
#          networks:
#            - my-network

  ts-food-map-service:
        build: ts-food-map-service
        image: containers.github.scch.at/contest/trainticket/ts-food-map-service:error-f4
        restart: always
        ports:
          - 18855:18855
        networks:
          - my-network

  ts-food-map-mongo:
          image: mongo:4.4
          networks:
            - my-network

  ts-route-plan-service:
          build: ts-route-plan-service
          image: containers.github.scch.at/contest/trainticket/ts-route-plan-service:error-f4
          restart: always
          ports:
            - 14578:14578
          networks:
            - my-network

  ts-food-service:
      build: ts-food-service
      image: containers.github.scch.at/contest/trainticket/ts-food-service:error-f4
      restart: always
      ports:
        - 18856:18856
      networks:
        - my-network

  ts-consign-service:
            build: ts-consign-service
            image: containers.github.scch.at/contest/trainticket/ts-consign-service:error-f4
            restart: always
            ports:
              - 16111:16111
            networks:
              - my-network

  ts-consign-mongo:
            image: mongo:4.4
            networks:
              - my-network

  ts-consign-price-service:
            build: ts-consign-price-service
            image: containers.github.scch.at/contest/trainticket/ts-consign-price-service:error-f4
            restart: always
            ports:
              - 16110:16110
            networks:
              - my-network

  ts-consign-price-mongo:
            image: mongo:4.4
            networks:
              - my-network

  ts-food-mongo:
            image: mongo:4.4
            networks:
              - my-network

  ts-admin-basic-info-service:
        build: ts-admin-basic-info-service
        image: containers.github.scch.at/contest/trainticket/ts-admin-basic-info-service:error-f4
        restart: always
        ports:
          - 18767:18767
        networks:
          - my-network

  ts-admin-order-service:
            build: ts-admin-order-service
            image: containers.github.scch.at/contest/trainticket/ts-admin-order-service:error-f4
            restart: always
            ports:
              - 16112:16112
            networks:
              - my-network

  ts-admin-route-service:
              build: ts-admin-route-service
              image: containers.github.scch.at/contest/trainticket/ts-admin-route-service:error-f4
              restart: always
              ports:
                - 16113:16113
              deploy:
                replicas: 1
                restart_policy:
                  condition: on-failure
              networks:
                - my-network

  ts-admin-travel-service:
                build: ts-admin-travel-service
                image: containers.github.scch.at/contest/trainticket/ts-admin-travel-service:error-f4
                restart: always
                ports:
                  - 16114:16114
                deploy:
                  replicas: 1
                  restart_policy:
                    condition: on-failure
                networks:
                  - my-network

  ts-admin-user-service:
                  build: ts-admin-user-service
                  image: containers.github.scch.at/contest/trainticket/ts-admin-user-service:error-f4
                  restart: always
                  ports:
                    - 16115:16115
                  deploy:
                    replicas: 1
                    restart_policy:
                      condition: on-failure
                  networks:
                    - my-network

networks:
    my-network:
      # driver: overlay
      driver: bridge





