# HTTP Server
server:
  port: 12032  # HTTP (Tomcat) port

spring:
  application:
    name: ts-order-other-service
  redis:
    host: redis
    port: 6379
  data:
    mongodb:
      host: ts-order-other-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017

