spring:

  application:
    name: ts-sso-service

  data:
    mongodb:
      host: ts-account-mongo
      database: ts
      port: 27017
  redis:
    host: ts-sso-redis
    port: 6379



  

# HTTP Server
server:
  port: 12349  # HTTP (Tomcat) port